version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    container_name: diabetes-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: always

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    container_name: diabetes-frontend
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - backend
    restart: always

networks:
  default:
    driver: bridge
