name: CD Pipeline

on:
  push:
    branches:
      - main  # Deploy only on merge to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Build and Push Backend Image
        run: |
          docker build -f docker/Dockerfile.backend -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/treatment-backend:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/treatment-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -f docker/Dockerfile.frontend -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/treatment-frontend:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/treatment-frontend:latest

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy treatment-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/treatment-backend:latest \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy treatment-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/treatment-frontend:latest \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated
